// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: command_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	CreateAuction(ctx context.Context, in *CreateAuctionRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateAuction(ctx context.Context, in *UpdateAuctionRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteAuction(ctx context.Context, in *DeleteAuctionRequest, opts ...grpc.CallOption) (*Response, error)
	AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteParticipant(ctx context.Context, in *DeleteParticipantRequest, opts ...grpc.CallOption) (*Response, error)
	AddLot(ctx context.Context, in *AddLotRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateLot(ctx context.Context, in *UpdateLotRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteLot(ctx context.Context, in *DeleteLotRequest, opts ...grpc.CallOption) (*Response, error)
	UploadMedia(ctx context.Context, opts ...grpc.CallOption) (CommandService_UploadMediaClient, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) CreateAuction(ctx context.Context, in *CreateAuctionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/CreateAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) UpdateAuction(ctx context.Context, in *UpdateAuctionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/UpdateAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) DeleteAuction(ctx context.Context, in *DeleteAuctionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/DeleteAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) AddParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/AddParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) DeleteParticipant(ctx context.Context, in *DeleteParticipantRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/DeleteParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) AddLot(ctx context.Context, in *AddLotRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/AddLot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) UpdateLot(ctx context.Context, in *UpdateLotRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/UpdateLot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) DeleteLot(ctx context.Context, in *DeleteLotRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.CommandService/DeleteLot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) UploadMedia(ctx context.Context, opts ...grpc.CallOption) (CommandService_UploadMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], "/protobuf.CommandService/UploadMedia", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandServiceUploadMediaClient{stream}
	return x, nil
}

type CommandService_UploadMediaClient interface {
	Send(*UploadMediaRequest) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type commandServiceUploadMediaClient struct {
	grpc.ClientStream
}

func (x *commandServiceUploadMediaClient) Send(m *UploadMediaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commandServiceUploadMediaClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility
type CommandServiceServer interface {
	CreateAuction(context.Context, *CreateAuctionRequest) (*Response, error)
	UpdateAuction(context.Context, *UpdateAuctionRequest) (*Response, error)
	DeleteAuction(context.Context, *DeleteAuctionRequest) (*Response, error)
	AddParticipant(context.Context, *AddParticipantRequest) (*Response, error)
	DeleteParticipant(context.Context, *DeleteParticipantRequest) (*Response, error)
	AddLot(context.Context, *AddLotRequest) (*Response, error)
	UpdateLot(context.Context, *UpdateLotRequest) (*Response, error)
	DeleteLot(context.Context, *DeleteLotRequest) (*Response, error)
	UploadMedia(CommandService_UploadMediaServer) error
}

// UnimplementedCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (UnimplementedCommandServiceServer) CreateAuction(context.Context, *CreateAuctionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuction not implemented")
}
func (UnimplementedCommandServiceServer) UpdateAuction(context.Context, *UpdateAuctionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAuction not implemented")
}
func (UnimplementedCommandServiceServer) DeleteAuction(context.Context, *DeleteAuctionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuction not implemented")
}
func (UnimplementedCommandServiceServer) AddParticipant(context.Context, *AddParticipantRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddParticipant not implemented")
}
func (UnimplementedCommandServiceServer) DeleteParticipant(context.Context, *DeleteParticipantRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteParticipant not implemented")
}
func (UnimplementedCommandServiceServer) AddLot(context.Context, *AddLotRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLot not implemented")
}
func (UnimplementedCommandServiceServer) UpdateLot(context.Context, *UpdateLotRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLot not implemented")
}
func (UnimplementedCommandServiceServer) DeleteLot(context.Context, *DeleteLotRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLot not implemented")
}
func (UnimplementedCommandServiceServer) UploadMedia(CommandService_UploadMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_CreateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).CreateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/CreateAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).CreateAuction(ctx, req.(*CreateAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_UpdateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).UpdateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/UpdateAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).UpdateAuction(ctx, req.(*UpdateAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_DeleteAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).DeleteAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/DeleteAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).DeleteAuction(ctx, req.(*DeleteAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_AddParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).AddParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/AddParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).AddParticipant(ctx, req.(*AddParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_DeleteParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).DeleteParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/DeleteParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).DeleteParticipant(ctx, req.(*DeleteParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_AddLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).AddLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/AddLot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).AddLot(ctx, req.(*AddLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_UpdateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).UpdateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/UpdateLot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).UpdateLot(ctx, req.(*UpdateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_DeleteLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).DeleteLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CommandService/DeleteLot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).DeleteLot(ctx, req.(*DeleteLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_UploadMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandServiceServer).UploadMedia(&commandServiceUploadMediaServer{stream})
}

type CommandService_UploadMediaServer interface {
	SendAndClose(*Response) error
	Recv() (*UploadMediaRequest, error)
	grpc.ServerStream
}

type commandServiceUploadMediaServer struct {
	grpc.ServerStream
}

func (x *commandServiceUploadMediaServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commandServiceUploadMediaServer) Recv() (*UploadMediaRequest, error) {
	m := new(UploadMediaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuction",
			Handler:    _CommandService_CreateAuction_Handler,
		},
		{
			MethodName: "UpdateAuction",
			Handler:    _CommandService_UpdateAuction_Handler,
		},
		{
			MethodName: "DeleteAuction",
			Handler:    _CommandService_DeleteAuction_Handler,
		},
		{
			MethodName: "AddParticipant",
			Handler:    _CommandService_AddParticipant_Handler,
		},
		{
			MethodName: "DeleteParticipant",
			Handler:    _CommandService_DeleteParticipant_Handler,
		},
		{
			MethodName: "AddLot",
			Handler:    _CommandService_AddLot_Handler,
		},
		{
			MethodName: "UpdateLot",
			Handler:    _CommandService_UpdateLot_Handler,
		},
		{
			MethodName: "DeleteLot",
			Handler:    _CommandService_DeleteLot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMedia",
			Handler:       _CommandService_UploadMedia_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "command_service.proto",
}
